---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template provisions the VenturaVPC Network Infrastructure
Metadata: {}
Parameters: {}
Mappings: {}
Conditions: {}
Resources:
  VenturaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
      - Key: Name
        Value: VenturaVPC
Outputs: {}
